import turtle

window = turtle.Screen()
window.title('Circles in Python')

circle_shape = turtle.Turtle()

circle_shape.penup()
circle_shape.goto(0,-100)
circle_shape.pendown()

circle_shape.begin_fill()
circle_shape.color("green")

circle_shape.left(20)
circle_shape.circle(90)

circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)
circle_shape.left(20)
circle_shape.circle(90)


circle_shape.end_fill()

circle_shape.hideturtle()
turtle.done()